// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "PDFGist";
inline constexpr char kVersion[] = "0.1.0";
inline constexpr std::int64_t kBuild = 1;
inline constexpr char kIdentifier[] = "site.jrtx.pdfgist";
inline constexpr char kReleaseChannel[] = "stable";

enum class SummarizeMode { page, selection, doc };

enum class TargetLanguage { zh, zh_hant, en, ja, ko, fr, de, es };

struct EditTextBox {
  std::int64_t page;
  std::int64_t x_ratio_milli;
  std::int64_t y_ratio_milli;
  std::string text;
  std::int64_t size;
};

struct EpubTocItem {
  std::string title;
  std::int64_t chapter;
  std::int64_t level;
};

struct EpubView {
  std::string title;
  std::int64_t chapters;
  std::vector<EpubTocItem> toc;
};

struct ProviderPreset {
  std::string id;
  std::string label;
  std::string base_url;
  std::string default_model;
  bool needs_key;
};

struct RecentEntry {
  std::string path;
  std::int64_t page;
  std::int64_t scroll_ratio_scaled;
  std::int64_t last_read_ms;
};

struct SettingsUpdate {
  std::string provider;
  std::string base_url;
  std::string model;
  TargetLanguage target_language;
  std::string view_mode;
  bool annotation_sidecar;
};

struct SettingsView {
  std::string provider;
  std::string base_url;
  std::string model;
  TargetLanguage target_language;
  std::string view_mode;
  bool annotation_sidecar;
  bool has_api_key;
  std::vector<RecentEntry> recent;
};

struct StreamChunk {
  std::int64_t request_id;
  std::string delta;
  bool is_reasoning;
};

struct StreamDone {
  std::int64_t request_id;
};

struct StreamError {
  std::int64_t request_id;
  std::string message;
};

struct StreamStart {
  std::int64_t request_id;
};

struct TestResult {
  bool ok;
  std::optional<std::string> error;
  std::optional<std::vector<std::string>> models;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode__List_String_(std::vector<std::string> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_String(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_List_String_(std::vector<std::vector<std::string>> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode__List_String_(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode_StreamStart(StreamStart const& v) { rivet::Value::List r; r.reserve(1); r.push_back(encode_Int64(v.request_id)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_Bytes(rivet::Bytes const& v) { return rivet::Value(v); }
inline rivet::Value encode_EditTextBox(EditTextBox const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_Int64(v.page)); r.push_back(encode_Int64(v.x_ratio_milli)); r.push_back(encode_Int64(v.y_ratio_milli)); r.push_back(encode_String(v.text)); r.push_back(encode_Int64(v.size)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_EditTextBox_(std::vector<EditTextBox> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_EditTextBox(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_Int64_(std::vector<std::int64_t> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_Int64(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_EpubTocItem(EpubTocItem const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_String(v.title)); r.push_back(encode_Int64(v.chapter)); r.push_back(encode_Int64(v.level)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_EpubTocItem_(std::vector<EpubTocItem> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_EpubTocItem(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_EpubView(EpubView const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_String(v.title)); r.push_back(encode_Int64(v.chapters)); r.push_back(encode__List_EpubTocItem_(v.toc)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_RecentEntry(RecentEntry const& v) { rivet::Value::List r; r.reserve(4); r.push_back(encode_String(v.path)); r.push_back(encode_Int64(v.page)); r.push_back(encode_Int64(v.scroll_ratio_scaled)); r.push_back(encode_Int64(v.last_read_ms)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_RecentEntry_(std::vector<RecentEntry> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_RecentEntry(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_TargetLanguage(TargetLanguage v) { switch (v) { case TargetLanguage::zh: return rivet::Value(std::string("zh")); case TargetLanguage::zh_hant: return rivet::Value(std::string("zh-hant")); case TargetLanguage::en: return rivet::Value(std::string("en")); case TargetLanguage::ja: return rivet::Value(std::string("ja")); case TargetLanguage::ko: return rivet::Value(std::string("ko")); case TargetLanguage::fr: return rivet::Value(std::string("fr")); case TargetLanguage::de: return rivet::Value(std::string("de")); case TargetLanguage::es: return rivet::Value(std::string("es")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode_SettingsView(SettingsView const& v) { rivet::Value::List r; r.reserve(8); r.push_back(encode_String(v.provider)); r.push_back(encode_String(v.base_url)); r.push_back(encode_String(v.model)); r.push_back(encode_TargetLanguage(v.target_language)); r.push_back(encode_String(v.view_mode)); r.push_back(encode_Bool(v.annotation_sidecar)); r.push_back(encode_Bool(v.has_api_key)); r.push_back(encode__List_RecentEntry_(v.recent)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Void() { return rivet::Value{}; }
inline rivet::Value encode_ProviderPreset(ProviderPreset const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_String(v.id)); r.push_back(encode_String(v.label)); r.push_back(encode_String(v.base_url)); r.push_back(encode_String(v.default_model)); r.push_back(encode_Bool(v.needs_key)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_ProviderPreset_(std::vector<ProviderPreset> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_ProviderPreset(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_SettingsUpdate(SettingsUpdate const& v) { rivet::Value::List r; r.reserve(6); r.push_back(encode_String(v.provider)); r.push_back(encode_String(v.base_url)); r.push_back(encode_String(v.model)); r.push_back(encode_TargetLanguage(v.target_language)); r.push_back(encode_String(v.view_mode)); r.push_back(encode_Bool(v.annotation_sidecar)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_SummarizeMode(SummarizeMode v) { switch (v) { case SummarizeMode::page: return rivet::Value(std::string("page")); case SummarizeMode::selection: return rivet::Value(std::string("selection")); case SummarizeMode::doc: return rivet::Value(std::string("doc")); } throw std::runtime_error("invalid Rivet enum value"); }
inline rivet::Value encode__Optional_String_(std::optional<std::string> const& v) { return v ? encode_String(*v) : rivet::Value{}; }
inline rivet::Value encode__Optional_List_String_(std::optional<std::vector<std::string>> const& v) { return v ? encode__List_String_(*v) : rivet::Value{}; }
inline rivet::Value encode_TestResult(TestResult const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_Bool(v.ok)); r.push_back(encode__Optional_String_(v.error)); r.push_back(encode__Optional_List_String_(v.models)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_StreamChunk(StreamChunk const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_Int64(v.request_id)); r.push_back(encode_String(v.delta)); r.push_back(encode_Bool(v.is_reasoning)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_StreamDone(StreamDone const& v) { rivet::Value::List r; r.reserve(1); r.push_back(encode_Int64(v.request_id)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_StreamError(StreamError const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode_Int64(v.request_id)); r.push_back(encode_String(v.message)); return rivet::Value(std::move(r)); }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::vector<std::string> decode__List_String_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List String)"); std::vector<std::string> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_String(x)); return r; }
inline std::vector<std::vector<std::string>> decode__List_List_String_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List (List String))"); std::vector<std::vector<std::string>> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode__List_String_(x)); return r; }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline StreamStart decode_StreamStart(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 1) throw std::runtime_error("Rivet result type mismatch: StreamStart"); return StreamStart{decode_Int64((*p)[0])}; }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline rivet::Bytes decode_Bytes(rivet::Value const& v) { if (auto p = std::get_if<rivet::Bytes>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bytes"); }
inline EditTextBox decode_EditTextBox(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: EditTextBox"); return EditTextBox{decode_Int64((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2]), decode_String((*p)[3]), decode_Int64((*p)[4])}; }
inline std::vector<EditTextBox> decode__List_EditTextBox_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List EditTextBox)"); std::vector<EditTextBox> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_EditTextBox(x)); return r; }
inline std::vector<std::int64_t> decode__List_Int64_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List Int64)"); std::vector<std::int64_t> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_Int64(x)); return r; }
inline EpubTocItem decode_EpubTocItem(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: EpubTocItem"); return EpubTocItem{decode_String((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2])}; }
inline std::vector<EpubTocItem> decode__List_EpubTocItem_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List EpubTocItem)"); std::vector<EpubTocItem> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_EpubTocItem(x)); return r; }
inline EpubView decode_EpubView(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: EpubView"); return EpubView{decode_String((*p)[0]), decode_Int64((*p)[1]), decode__List_EpubTocItem_((*p)[2])}; }
inline RecentEntry decode_RecentEntry(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 4) throw std::runtime_error("Rivet result type mismatch: RecentEntry"); return RecentEntry{decode_String((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2]), decode_Int64((*p)[3])}; }
inline std::vector<RecentEntry> decode__List_RecentEntry_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List RecentEntry)"); std::vector<RecentEntry> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_RecentEntry(x)); return r; }
inline TargetLanguage decode_TargetLanguage(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "zh") return TargetLanguage::zh; if (*p == "zh-hant") return TargetLanguage::zh_hant; if (*p == "en") return TargetLanguage::en; if (*p == "ja") return TargetLanguage::ja; if (*p == "ko") return TargetLanguage::ko; if (*p == "fr") return TargetLanguage::fr; if (*p == "de") return TargetLanguage::de; if (*p == "es") return TargetLanguage::es; } throw std::runtime_error("Rivet result type mismatch: TargetLanguage"); }
inline SettingsView decode_SettingsView(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 8) throw std::runtime_error("Rivet result type mismatch: SettingsView"); return SettingsView{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_TargetLanguage((*p)[3]), decode_String((*p)[4]), decode_Bool((*p)[5]), decode_Bool((*p)[6]), decode__List_RecentEntry_((*p)[7])}; }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
inline ProviderPreset decode_ProviderPreset(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: ProviderPreset"); return ProviderPreset{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_String((*p)[3]), decode_Bool((*p)[4])}; }
inline std::vector<ProviderPreset> decode__List_ProviderPreset_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List ProviderPreset)"); std::vector<ProviderPreset> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_ProviderPreset(x)); return r; }
inline SettingsUpdate decode_SettingsUpdate(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 6) throw std::runtime_error("Rivet result type mismatch: SettingsUpdate"); return SettingsUpdate{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_TargetLanguage((*p)[3]), decode_String((*p)[4]), decode_Bool((*p)[5])}; }
inline SummarizeMode decode_SummarizeMode(rivet::Value const& v) { auto p = std::get_if<std::string>(&v.data); if (p) { if (*p == "page") return SummarizeMode::page; if (*p == "selection") return SummarizeMode::selection; if (*p == "doc") return SummarizeMode::doc; } throw std::runtime_error("Rivet result type mismatch: SummarizeMode"); }
inline std::optional<std::string> decode__Optional_String_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_String(v); }
inline std::optional<std::vector<std::string>> decode__Optional_List_String_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode__List_String_(v); }
inline TestResult decode_TestResult(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: TestResult"); return TestResult{decode_Bool((*p)[0]), decode__Optional_String_((*p)[1]), decode__Optional_List_String_((*p)[2])}; }
inline StreamChunk decode_StreamChunk(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: StreamChunk"); return StreamChunk{decode_Int64((*p)[0]), decode_String((*p)[1]), decode_Bool((*p)[2])}; }
inline StreamDone decode_StreamDone(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 1) throw std::runtime_error("Rivet result type mismatch: StreamDone"); return StreamDone{decode_Int64((*p)[0])}; }
inline StreamError decode_StreamError(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: StreamError"); return StreamError{decode_Int64((*p)[0]), decode_String((*p)[1])}; }
}  // namespace detail

struct Stream_chunkEvent { StreamChunk value; };
struct Stream_doneEvent { StreamDone value; };
struct Stream_errorEvent { StreamError value; };
using Event = std::variant<Stream_chunkEvent, Stream_doneEvent, Stream_errorEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "stream-chunk") return Event{Stream_chunkEvent{detail::decode_StreamChunk(value)}};
  if (name == "stream-done") return Event{Stream_doneEvent{detail::decode_StreamDone(value)}};
  if (name == "stream-error") return Event{Stream_errorEvent{detail::decode_StreamError(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::windows::Backend& backend) : backend_(backend) {}

  std::future<StreamStart> chat(std::string context_text, std::string context_label, std::vector<std::vector<std::string>> history, std::string user_message) { auto raw = backend_.call("chat", rivet::Value::List{detail::encode_String(context_text), detail::encode_String(context_label), detail::encode__List_List_String_(history), detail::encode_String(user_message)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> StreamStart { return detail::decode_StreamStart(raw.get()); }); }
  [[nodiscard]] std::uint64_t chat_async(std::string context_text, std::string context_label, std::vector<std::vector<std::string>> history, std::string user_message, std::function<void(Result<StreamStart>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("chat", rivet::Value::List{detail::encode_String(context_text), detail::encode_String(context_label), detail::encode__List_List_String_(history), detail::encode_String(user_message)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<StreamStart> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_StreamStart(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> check_updates(bool force) { auto raw = backend_.call("check-updates", rivet::Value::List{detail::encode_Bool(force)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t check_updates_async(bool force, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("check-updates", rivet::Value::List{detail::encode_Bool(force)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> edit_append_doc(std::string path, std::string other_path) { auto raw = backend_.call("edit-append-doc", rivet::Value::List{detail::encode_String(path), detail::encode_String(other_path)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t edit_append_doc_async(std::string path, std::string other_path, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("edit-append-doc", rivet::Value::List{detail::encode_String(path), detail::encode_String(other_path)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> edit_bake_text(std::string path, std::string watermark_text, std::int64_t watermark_size, std::int64_t watermark_opacity_milli, std::vector<EditTextBox> boxes) { auto raw = backend_.call("edit-bake-text", rivet::Value::List{detail::encode_String(path), detail::encode_String(watermark_text), detail::encode_Int64(watermark_size), detail::encode_Int64(watermark_opacity_milli), detail::encode__List_EditTextBox_(boxes)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t edit_bake_text_async(std::string path, std::string watermark_text, std::int64_t watermark_size, std::int64_t watermark_opacity_milli, std::vector<EditTextBox> boxes, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("edit-bake-text", rivet::Value::List{detail::encode_String(path), detail::encode_String(watermark_text), detail::encode_Int64(watermark_size), detail::encode_Int64(watermark_opacity_milli), detail::encode__List_EditTextBox_(boxes)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> edit_delete_pages(std::string path, std::vector<std::int64_t> pages) { auto raw = backend_.call("edit-delete-pages", rivet::Value::List{detail::encode_String(path), detail::encode__List_Int64_(pages)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t edit_delete_pages_async(std::string path, std::vector<std::int64_t> pages, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("edit-delete-pages", rivet::Value::List{detail::encode_String(path), detail::encode__List_Int64_(pages)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> edit_extract_pages(std::string path, std::vector<std::int64_t> pages) { auto raw = backend_.call("edit-extract-pages", rivet::Value::List{detail::encode_String(path), detail::encode__List_Int64_(pages)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t edit_extract_pages_async(std::string path, std::vector<std::int64_t> pages, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("edit-extract-pages", rivet::Value::List{detail::encode_String(path), detail::encode__List_Int64_(pages)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> edit_insert_blank_after(std::string path, std::int64_t page) { auto raw = backend_.call("edit-insert-blank-after", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(page)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t edit_insert_blank_after_async(std::string path, std::int64_t page, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("edit-insert-blank-after", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(page)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> edit_rotate_pages(std::string path, std::vector<std::int64_t> pages, std::int64_t delta) { auto raw = backend_.call("edit-rotate-pages", rivet::Value::List{detail::encode_String(path), detail::encode__List_Int64_(pages), detail::encode_Int64(delta)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t edit_rotate_pages_async(std::string path, std::vector<std::int64_t> pages, std::int64_t delta, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("edit-rotate-pages", rivet::Value::List{detail::encode_String(path), detail::encode__List_Int64_(pages), detail::encode_Int64(delta)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> epub_chapter_html(std::string path, std::int64_t index) { auto raw = backend_.call("epub-chapter-html", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(index)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t epub_chapter_html_async(std::string path, std::int64_t index, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("epub-chapter-html", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(index)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> epub_chapter_text(std::string path, std::int64_t index) { auto raw = backend_.call("epub-chapter-text", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(index)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t epub_chapter_text_async(std::string path, std::int64_t index, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("epub-chapter-text", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(index)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> epub_doc_text(std::string path, std::int64_t max_chapters, std::int64_t cap_chars) { auto raw = backend_.call("epub-doc-text", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(max_chapters), detail::encode_Int64(cap_chars)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t epub_doc_text_async(std::string path, std::int64_t max_chapters, std::int64_t cap_chars, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("epub-doc-text", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(max_chapters), detail::encode_Int64(cap_chars)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<EpubView> epub_open(std::string path) { auto raw = backend_.call("epub-open", rivet::Value::List{detail::encode_String(path)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> EpubView { return detail::decode_EpubView(raw.get()); }); }
  [[nodiscard]] std::uint64_t epub_open_async(std::string path, std::function<void(Result<EpubView>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("epub-open", rivet::Value::List{detail::encode_String(path)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<EpubView> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_EpubView(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> get_annotations(std::string pdf_path, bool sidecar) { auto raw = backend_.call("get-annotations", rivet::Value::List{detail::encode_String(pdf_path), detail::encode_Bool(sidecar)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_annotations_async(std::string pdf_path, bool sidecar, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-annotations", rivet::Value::List{detail::encode_String(pdf_path), detail::encode_Bool(sidecar)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<RecentEntry>> get_recents() { auto raw = backend_.call("get-recents", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<RecentEntry> { return detail::decode__List_RecentEntry_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_recents_async(std::function<void(Result<std::vector<RecentEntry>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-recents", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<RecentEntry>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_RecentEntry_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<SettingsView> get_settings() { auto raw = backend_.call("get-settings", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> SettingsView { return detail::decode_SettingsView(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_settings_async(std::function<void(Result<SettingsView>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-settings", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<SettingsView> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_SettingsView(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> initialize() { auto raw = backend_.call("initialize", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t initialize_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("initialize", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<ProviderPreset>> list_presets() { auto raw = backend_.call("list-presets", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<ProviderPreset> { return detail::decode__List_ProviderPreset_(raw.get()); }); }
  [[nodiscard]] std::uint64_t list_presets_async(std::function<void(Result<std::vector<ProviderPreset>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("list-presets", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<ProviderPreset>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_ProviderPreset_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> save_api_key(std::string key) { auto raw = backend_.call("save-api-key", rivet::Value::List{detail::encode_String(key)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t save_api_key_async(std::string key, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("save-api-key", rivet::Value::List{detail::encode_String(key)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<SettingsView> save_settings(SettingsUpdate update) { auto raw = backend_.call("save-settings", rivet::Value::List{detail::encode_SettingsUpdate(update)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> SettingsView { return detail::decode_SettingsView(raw.get()); }); }
  [[nodiscard]] std::uint64_t save_settings_async(SettingsUpdate update, std::function<void(Result<SettingsView>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("save-settings", rivet::Value::List{detail::encode_SettingsUpdate(update)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<SettingsView> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_SettingsView(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> set_annotations(std::string pdf_path, bool sidecar, rivet::Bytes data) { auto raw = backend_.call("set-annotations", rivet::Value::List{detail::encode_String(pdf_path), detail::encode_Bool(sidecar), detail::encode_Bytes(data)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_annotations_async(std::string pdf_path, bool sidecar, rivet::Bytes data, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set-annotations", rivet::Value::List{detail::encode_String(pdf_path), detail::encode_Bool(sidecar), detail::encode_Bytes(data)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> set_locale(std::string code) { auto raw = backend_.call("set-locale", rivet::Value::List{detail::encode_String(code)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_locale_async(std::string code, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set-locale", rivet::Value::List{detail::encode_String(code)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<std::string>> split_paragraphs(std::string text) { auto raw = backend_.call("split-paragraphs", rivet::Value::List{detail::encode_String(text)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<std::string> { return detail::decode__List_String_(raw.get()); }); }
  [[nodiscard]] std::uint64_t split_paragraphs_async(std::string text, std::function<void(Result<std::vector<std::string>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("split-paragraphs", rivet::Value::List{detail::encode_String(text)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<std::string>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_String_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> start_download() { auto raw = backend_.call("start-download", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t start_download_async(std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("start-download", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> stop_stream(std::int64_t request_id) { auto raw = backend_.call("stop-stream", rivet::Value::List{detail::encode_Int64(request_id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t stop_stream_async(std::int64_t request_id, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("stop-stream", rivet::Value::List{detail::encode_Int64(request_id)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<StreamStart> summarize_text(std::string text, SummarizeMode mode) { auto raw = backend_.call("summarize-text", rivet::Value::List{detail::encode_String(text), detail::encode_SummarizeMode(mode)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> StreamStart { return detail::decode_StreamStart(raw.get()); }); }
  [[nodiscard]] std::uint64_t summarize_text_async(std::string text, SummarizeMode mode, std::function<void(Result<StreamStart>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("summarize-text", rivet::Value::List{detail::encode_String(text), detail::encode_SummarizeMode(mode)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<StreamStart> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_StreamStart(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<TestResult> test_connection(std::string base_url, std::string api_key, std::string model) { auto raw = backend_.call("test-connection", rivet::Value::List{detail::encode_String(base_url), detail::encode_String(api_key), detail::encode_String(model)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> TestResult { return detail::decode_TestResult(raw.get()); }); }
  [[nodiscard]] std::uint64_t test_connection_async(std::string base_url, std::string api_key, std::string model, std::function<void(Result<TestResult>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("test-connection", rivet::Value::List{detail::encode_String(base_url), detail::encode_String(api_key), detail::encode_String(model)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<TestResult> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_TestResult(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<StreamStart> translate_text(std::string text, TargetLanguage target) { auto raw = backend_.call("translate-text", rivet::Value::List{detail::encode_String(text), detail::encode_TargetLanguage(target)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> StreamStart { return detail::decode_StreamStart(raw.get()); }); }
  [[nodiscard]] std::uint64_t translate_text_async(std::string text, TargetLanguage target, std::function<void(Result<StreamStart>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("translate-text", rivet::Value::List{detail::encode_String(text), detail::encode_TargetLanguage(target)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<StreamStart> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_StreamStart(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> update_recents(std::string path, std::int64_t page, std::int64_t scroll_ratio_scaled) { auto raw = backend_.call("update-recents", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(page), detail::encode_Int64(scroll_ratio_scaled)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_recents_async(std::string path, std::int64_t page, std::int64_t scroll_ratio_scaled, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update-recents", rivet::Value::List{detail::encode_String(path), detail::encode_Int64(page), detail::encode_Int64(scroll_ratio_scaled)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> update_state() { auto raw = backend_.call("update-state", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t update_state_async(std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("update-state", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<std::string> get_backend_locale() { auto raw = backend_.get_state("backend-locale"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_backend_locale_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("backend-locale", [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> set_backend_locale(std::string value) { auto raw = backend_.set_state("backend-locale", detail::encode_String(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_backend_locale_async(std::string value, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("backend-locale", detail::encode_String(value), [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::windows::Backend& backend_;
};

}  // namespace rivet_app
