// Generated from shared/i18n/{zh,en}.json — the single i18n source.
// Do not edit; run: node scripts/gen-swift-strings.mjs

enum L10n {
    nonisolated(unsafe) static var language: String = "zh"

    private static let zh: [String: String] = [
    "app.name": "PDFGist",
    "backend.error.bad-annotations": "批注数据格式不正确",
    "backend.error.connect": "连接失败：{0}",
    "backend.error.connect-timeout": "连接失败：连接超时（{0} 秒）",
    "backend.error.http-status": "HTTP {0}",
    "backend.error.http-status-body": "HTTP {0}：{1}（POST {2}）",
    "backend.error.parse-annotations": "批注文件解析失败：{0}",
    "backend.error.parse-response": "解析响应失败：{0}",
    "backend.error.parse-settings": "设置文件解析失败：{0}",
    "backend.error.read-annotations": "读取批注失败：{0}",
    "backend.error.read-response": "读取响应失败：{0}",
    "backend.error.read-settings": "读取设置失败：{0}",
    "backend.error.save-annotations": "保存批注失败：{0}",
    "backend.error.sse-line-too-long": "响应数据异常（单行过长）",
    "backend.error.write-settings": "写入设置失败：{0}",
    "backend.provider.custom": "自定义",
    "backend.provider.deepseek": "DeepSeek",
    "backend.provider.doubao": "豆包（火山方舟）",
    "backend.provider.doubao-coding": "豆包 Coding 套餐（火山方舟）",
    "backend.provider.glm-coding": "GLM Coding 套餐（智谱）",
    "backend.provider.kimi-coding": "Kimi Code 套餐（Moonshot）",
    "backend.provider.moonshot": "Moonshot Kimi",
    "backend.provider.ollama": "Ollama（本地）",
    "backend.provider.openai": "OpenAI",
    "backend.provider.qwen": "通义千问 Qwen",
    "backend.provider.siliconflow": "SiliconFlow 硅基流动",
    "backend.provider.zhipu": "智谱 GLM",
    "backend.stream.no-content": "（无返回内容）",
    "backend.stream.stopped": "（已停止）",
    "backend.stream.thinking": "思考中…",
    "ui.card.copied": "已复制",
    "ui.card.copy": "复制",
    "ui.card.stop": "停止",
    "ui.chat.history-cleared": "已切换范围，历史仅作参考",
    "ui.chat.need-selection": "（先在 PDF 中选择一段文本，再切换到「选区」范围）",
    "ui.chat.placeholder": "基于文档内容提问…",
    "ui.chat.scope": "上下文范围",
    "ui.chat.scope.doc": "全文",
    "ui.chat.scope.page": "当前页",
    "ui.chat.scope.selection": "选区",
    "ui.chat.send": "发送",
    "ui.chat.stop": "停止",
    "ui.drop": "松开以打开 PDF",
    "ui.forms.choice-placeholder": "选项值（需与表单选项完全一致）",
    "ui.forms.count": "共 {0} 个字段",
    "ui.forms.empty": "本文档没有可填写的表单字段",
    "ui.forms.export": "导出填写后的 PDF",
    "ui.forms.export-cancelled": "已取消导出",
    "ui.forms.export-disk-only": "仅支持从磁盘打开的 PDF 导出",
    "ui.forms.export-failed": "导出失败：{0}",
    "ui.forms.export-none": "本文档没有表单字段",
    "ui.forms.export-ok": "✓ 已导出 {0} 个字段",
    "ui.forms.export-skipped": "✓ 已导出（填写 {0} 个，跳过 {1} 个：{2}）",
    "ui.forms.export-suffix": "-已填写",
    "ui.forms.generating": "正在生成…",
    "ui.forms.type-check": "勾选",
    "ui.forms.type-choice": "选择",
    "ui.forms.type-text": "文本",
    "ui.menu.copy": "复制",
    "ui.menu.document": "文档",
    "ui.menu.highlight-blue": "高亮（蓝）",
    "ui.menu.highlight-green": "高亮（绿）",
    "ui.menu.highlight-yellow": "高亮（黄）",
    "ui.menu.strike": "删除线",
    "ui.menu.translate": "翻译",
    "ui.menu.underline": "下划线",
    "ui.menu.view": "显示",
    "ui.need.document": "先打开一个 PDF",
    "ui.need.selection": "先在 PDF 中选择一段文本",
    "ui.notes.bookmark-empty": "点工具栏书签按钮收藏当前页（⌘B）",
    "ui.notes.bookmark-remove": "删除书签",
    "ui.notes.bookmarks": "书签",
    "ui.notes.delete-btn": "删",
    "ui.notes.empty": "在正文中划选文本即可高亮并写笔记；高亮支持三色",
    "ui.notes.page": "第 {0} 页",
    "ui.notes.translate-btn": "译",
    "ui.open-failed": "打开失败：{0}",
    "ui.password.cancel": "取消",
    "ui.password.ok": "打开",
    "ui.password.title": "请输入打开密码",
    "ui.password.wrong": "密码错误，请重试",
    "ui.settings.api-key": "API Key",
    "ui.settings.api-key-saved": "已保存（输入新 Key 覆盖）",
    "ui.settings.base-url": "Base URL",
    "ui.settings.fetch-models": "拉取模型",
    "ui.settings.fetching": "正在拉取模型列表…",
    "ui.settings.model": "模型",
    "ui.settings.need-config": "请先完成服务商配置并保存",
    "ui.settings.preset": "服务商预设",
    "ui.settings.privacy": "隐私说明：文档内容仅发送给你配置的服务商；API Key 只保存在本机。",
    "ui.settings.save": "保存设置",
    "ui.settings.save-failed": "保存失败：{0}",
    "ui.settings.saved": "✓ 已保存",
    "ui.settings.sidecar": "批注保存到 PDF 旁（.pdfgist.json，便于网盘同步）",
    "ui.settings.target-language": "目标语言",
    "ui.settings.test": "测试连接",
    "ui.settings.test-ok": "✓ 连接正常，共 {0} 个模型",
    "ui.settings.test-ok-no-list": "✓ 连接正常（未返回模型列表，可手填模型名）",
    "ui.settings.view-double": "双页",
    "ui.settings.view-mode": "页面显示",
    "ui.settings.view-single": "单页",
    "ui.summarize.doc": "全文总结",
    "ui.summarize.doc-meta": "前 {0} 页",
    "ui.summarize.page": "本页总结",
    "ui.summarize.page-title": "第 {0} 页总结",
    "ui.summarize.selection": "选区总结",
    "ui.tab.chat": "对话",
    "ui.tab.forms": "表单",
    "ui.tab.notes": "批注",
    "ui.tab.settings": "设置",
    "ui.tab.summarize": "总结",
    "ui.tab.translate": "翻译",
    "ui.toolbar.ai": "AI 助手",
    "ui.toolbar.bookmark": "书签当前页（⌘B）",
    "ui.toolbar.find": "搜索（⌘F）",
    "ui.toolbar.open": "打开 PDF（⌘O）",
    "ui.toolbar.panel": "缩略图 / 目录",
    "ui.toolbar.tab-close": "关闭标签页（⌘W）",
    "ui.toolbar.theme-dark": "深色",
    "ui.toolbar.theme-light": "浅色",
    "ui.translate.empty-page": "第 {0} 页没有可提取的文本（可能是扫描件）",
    "ui.translate.page": "本页翻译",
    "ui.translate.page-title": "第 {0} 页翻译",
    "ui.viewer.find-placeholder": "搜索",
    "ui.viewer.fit": "适应宽度",
    "ui.viewer.outline": "目录",
    "ui.viewer.outline-empty": "本文档没有目录",
    "ui.viewer.pdf-info": "PDF · {0} 页",
    "ui.viewer.recents": "最近打开",
    "ui.viewer.thumbs": "缩略图",
    "ui.welcome.continue": "继续阅读",
    "ui.welcome.feature1": "划词翻译 · 一键总结 · 与文档对话",
    "ui.welcome.feature2": "全文搜索 · 缩略图导航 · 深色模式",
    "ui.welcome.feature3": "GLM / DeepSeek / Qwen / Kimi / Ollama，Key 只存本机",
    "ui.welcome.hints": "⌘O 打开 · ⌘F 搜索 · ⌘滚轮 缩放 · 划词翻译",
    "ui.welcome.open": "打开 PDF 文件",
    "ui.welcome.or-drag": "或拖到窗口任意位置",
    "ui.welcome.recent-meta": "第 {0} 页 · {1}月{2}日",
    "ui.welcome.tagline": "接入自己大模型的 AI PDF 阅读器",
    ]

    private static let en: [String: String] = [
    "app.name": "PDFGist",
    "backend.error.bad-annotations": "Invalid annotations data format",
    "backend.error.connect": "Connection failed: {0}",
    "backend.error.connect-timeout": "Connection failed: timed out after {0} s",
    "backend.error.http-status": "HTTP {0}",
    "backend.error.http-status-body": "HTTP {0}: {1} (POST {2})",
    "backend.error.parse-annotations": "Failed to parse annotations file: {0}",
    "backend.error.parse-response": "Failed to parse response: {0}",
    "backend.error.parse-settings": "Failed to parse settings file: {0}",
    "backend.error.read-annotations": "Failed to read annotations: {0}",
    "backend.error.read-response": "Failed to read response: {0}",
    "backend.error.read-settings": "Failed to read settings: {0}",
    "backend.error.save-annotations": "Failed to save annotations: {0}",
    "backend.error.sse-line-too-long": "Malformed response (single line too long)",
    "backend.error.write-settings": "Failed to write settings: {0}",
    "backend.provider.custom": "Custom",
    "backend.provider.deepseek": "DeepSeek",
    "backend.provider.doubao": "Doubao (Volcano Ark)",
    "backend.provider.doubao-coding": "Doubao Coding Plan (Volcano Ark)",
    "backend.provider.glm-coding": "GLM Coding Plan (Zhipu)",
    "backend.provider.kimi-coding": "Kimi Code Plan (Moonshot)",
    "backend.provider.moonshot": "Moonshot Kimi",
    "backend.provider.ollama": "Ollama (local)",
    "backend.provider.openai": "OpenAI",
    "backend.provider.qwen": "Qwen (Alibaba)",
    "backend.provider.siliconflow": "SiliconFlow",
    "backend.provider.zhipu": "Zhipu GLM",
    "backend.stream.no-content": "(No content returned)",
    "backend.stream.stopped": "(Stopped)",
    "backend.stream.thinking": "Thinking…",
    "ui.card.copied": "Copied",
    "ui.card.copy": "Copy",
    "ui.card.stop": "Stop",
    "ui.chat.history-cleared": "Scope changed; history is reference only",
    "ui.chat.need-selection": "(Select some text in the PDF first, then switch to the Selection scope)",
    "ui.chat.placeholder": "Ask about the document…",
    "ui.chat.scope": "Context scope",
    "ui.chat.scope.doc": "Document",
    "ui.chat.scope.page": "Current page",
    "ui.chat.scope.selection": "Selection",
    "ui.chat.send": "Send",
    "ui.chat.stop": "Stop",
    "ui.drop": "Drop to open the PDF",
    "ui.forms.choice-placeholder": "Option value (must match the form options exactly)",
    "ui.forms.count": "{0} field(s)",
    "ui.forms.empty": "No fillable form fields in this document",
    "ui.forms.export": "Export Filled PDF",
    "ui.forms.export-cancelled": "Export cancelled",
    "ui.forms.export-disk-only": "Export only works for PDFs opened from disk",
    "ui.forms.export-failed": "Export failed: {0}",
    "ui.forms.export-none": "This document has no form fields",
    "ui.forms.export-ok": "✓ Exported {0} field(s)",
    "ui.forms.export-skipped": "✓ Exported ({0} filled, {1} skipped: {2})",
    "ui.forms.export-suffix": "- filled",
    "ui.forms.generating": "Generating…",
    "ui.forms.type-check": "Check",
    "ui.forms.type-choice": "Choice",
    "ui.forms.type-text": "Text",
    "ui.menu.copy": "Copy",
    "ui.menu.document": "Document",
    "ui.menu.highlight-blue": "Highlight (blue)",
    "ui.menu.highlight-green": "Highlight (green)",
    "ui.menu.highlight-yellow": "Highlight (yellow)",
    "ui.menu.strike": "Strikeout",
    "ui.menu.translate": "Translate",
    "ui.menu.underline": "Underline",
    "ui.menu.view": "View",
    "ui.need.document": "Open a PDF first",
    "ui.need.selection": "Select some text in the PDF first",
    "ui.notes.bookmark-empty": "Use the toolbar bookmark button (⌘B) to save the current page",
    "ui.notes.bookmark-remove": "Remove bookmark",
    "ui.notes.bookmarks": "Bookmarks",
    "ui.notes.delete-btn": "✕",
    "ui.notes.empty": "Select text in the document to highlight it; highlights support three colors",
    "ui.notes.page": "Page {0}",
    "ui.notes.translate-btn": "T",
    "ui.open-failed": "Failed to open: {0}",
    "ui.password.cancel": "Cancel",
    "ui.password.ok": "Unlock",
    "ui.password.title": "Enter the open password",
    "ui.password.wrong": "Wrong password, try again",
    "ui.settings.api-key": "API Key",
    "ui.settings.api-key-saved": "Saved (enter a new key to replace)",
    "ui.settings.base-url": "Base URL",
    "ui.settings.fetch-models": "Fetch models",
    "ui.settings.fetching": "Fetching model list…",
    "ui.settings.model": "Model",
    "ui.settings.need-config": "Finish the provider configuration and save first",
    "ui.settings.preset": "Provider preset",
    "ui.settings.privacy": "Privacy: document content is sent only to the provider you configure; the API key never leaves this machine.",
    "ui.settings.save": "Save settings",
    "ui.settings.save-failed": "Save failed: {0}",
    "ui.settings.saved": "✓ Saved",
    "ui.settings.sidecar": "Store annotations next to the PDF (.pdfgist.json, syncs with cloud drives)",
    "ui.settings.target-language": "Target language",
    "ui.settings.test": "Test connection",
    "ui.settings.test-ok": "✓ Connected, {0} models",
    "ui.settings.test-ok-no-list": "✓ Connected (no model list returned; enter the model name manually)",
    "ui.settings.view-double": "Two-up",
    "ui.settings.view-mode": "Page layout",
    "ui.settings.view-single": "Single page",
    "ui.summarize.doc": "Summarize document",
    "ui.summarize.doc-meta": "first {0} pages",
    "ui.summarize.page": "Summarize page",
    "ui.summarize.page-title": "Page {0} summary",
    "ui.summarize.selection": "Summarize selection",
    "ui.tab.chat": "Chat",
    "ui.tab.forms": "Forms",
    "ui.tab.notes": "Notes",
    "ui.tab.settings": "Settings",
    "ui.tab.summarize": "Summarize",
    "ui.tab.translate": "Translate",
    "ui.toolbar.ai": "AI Assistant",
    "ui.toolbar.bookmark": "Bookmark this page (⌘B)",
    "ui.toolbar.find": "Search (⌘F)",
    "ui.toolbar.open": "Open PDF (⌘O)",
    "ui.toolbar.panel": "Thumbnails / Outline",
    "ui.toolbar.tab-close": "Close tab (⌘W)",
    "ui.toolbar.theme-dark": "Dark",
    "ui.toolbar.theme-light": "Light",
    "ui.translate.empty-page": "Page {0} has no extractable text (possibly a scanned page)",
    "ui.translate.page": "Translate page",
    "ui.translate.page-title": "Page {0} translation",
    "ui.viewer.find-placeholder": "Search",
    "ui.viewer.fit": "Fit width",
    "ui.viewer.outline": "Outline",
    "ui.viewer.outline-empty": "This document has no outline",
    "ui.viewer.pdf-info": "PDF · {0} pages",
    "ui.viewer.recents": "Recent",
    "ui.viewer.thumbs": "Thumbnails",
    "ui.welcome.continue": "Continue reading",
    "ui.welcome.feature1": "Selection translation · one-click summaries · chat with the document",
    "ui.welcome.feature2": "Full-text search · thumbnail navigation · dark mode",
    "ui.welcome.feature3": "GLM / DeepSeek / Qwen / Kimi / Ollama — keys stay on this machine",
    "ui.welcome.hints": "⌘O Open · ⌘F Search · ⌘Scroll Zoom · Select to translate",
    "ui.welcome.open": "Open PDF File",
    "ui.welcome.or-drag": "or drag a file anywhere into the window",
    "ui.welcome.recent-meta": "page {0} · {1}/{2}",
    "ui.welcome.tagline": "An AI PDF reader that brings your own model",
    ]

    /// Look up a key in the active language, falling back to zh then the key
    /// itself. "{0}"-style placeholders are substituted from the args.
    static func t(_ key: String, _ args: String...) -> String {
        let table = language == "en" ? en : zh
        var s = table[key] ?? zh[key] ?? key
        for (i, arg) in args.enumerated() {
            s = s.replacingOccurrences(of: "{\(i)}", with: arg)
        }
        return s
    }
}
