// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "PDFGist"
    public static let version = "1.2.3"
    public static let build: Int64 = 1
    public static let identifier = "site.jrtx.pdfgist"
    public static let releaseChannel = "stable"
}

public enum SummarizeMode: String, Sendable {
    case page = "page"
    case selection = "selection"
    case doc = "doc"
}

public enum TargetLanguage: String, Sendable {
    case zh = "zh"
    case zh_hant = "zh-hant"
    case en = "en"
    case ja = "ja"
    case ko = "ko"
    case fr = "fr"
    case de = "de"
    case es = "es"
}

public struct EditTextBox: Sendable {
    public let page: Int64
    public let x_ratio_milli: Int64
    public let y_ratio_milli: Int64
    public let text: String
    public let size: Int64
    public init(page: Int64, x_ratio_milli: Int64, y_ratio_milli: Int64, text: String, size: Int64) {
        self.page = page
        self.x_ratio_milli = x_ratio_milli
        self.y_ratio_milli = y_ratio_milli
        self.text = text
        self.size = size
    }
}

public struct EpubTocItem: Sendable {
    public let title: String
    public let chapter: Int64
    public let level: Int64
    public init(title: String, chapter: Int64, level: Int64) {
        self.title = title
        self.chapter = chapter
        self.level = level
    }
}

public struct EpubView: Sendable {
    public let title: String
    public let chapters: Int64
    public let toc: [EpubTocItem]
    public init(title: String, chapters: Int64, toc: [EpubTocItem]) {
        self.title = title
        self.chapters = chapters
        self.toc = toc
    }
}

public struct ProviderPreset: Sendable {
    public let id: String
    public let label: String
    public let base_url: String
    public let default_model: String
    public let needs_key: Bool
    public init(id: String, label: String, base_url: String, default_model: String, needs_key: Bool) {
        self.id = id
        self.label = label
        self.base_url = base_url
        self.default_model = default_model
        self.needs_key = needs_key
    }
}

public struct RecentEntry: Sendable {
    public let path: String
    public let page: Int64
    public let scroll_ratio_scaled: Int64
    public let last_read_ms: Int64
    public init(path: String, page: Int64, scroll_ratio_scaled: Int64, last_read_ms: Int64) {
        self.path = path
        self.page = page
        self.scroll_ratio_scaled = scroll_ratio_scaled
        self.last_read_ms = last_read_ms
    }
}

public struct SettingsUpdate: Sendable {
    public let provider: String
    public let base_url: String
    public let model: String
    public let target_language: TargetLanguage
    public let view_mode: String
    public let annotation_sidecar: Bool
    public init(provider: String, base_url: String, model: String, target_language: TargetLanguage, view_mode: String, annotation_sidecar: Bool) {
        self.provider = provider
        self.base_url = base_url
        self.model = model
        self.target_language = target_language
        self.view_mode = view_mode
        self.annotation_sidecar = annotation_sidecar
    }
}

public struct SettingsView: Sendable {
    public let provider: String
    public let base_url: String
    public let model: String
    public let target_language: TargetLanguage
    public let view_mode: String
    public let annotation_sidecar: Bool
    public let has_api_key: Bool
    public let recent: [RecentEntry]
    public init(provider: String, base_url: String, model: String, target_language: TargetLanguage, view_mode: String, annotation_sidecar: Bool, has_api_key: Bool, recent: [RecentEntry]) {
        self.provider = provider
        self.base_url = base_url
        self.model = model
        self.target_language = target_language
        self.view_mode = view_mode
        self.annotation_sidecar = annotation_sidecar
        self.has_api_key = has_api_key
        self.recent = recent
    }
}

public struct StreamChunk: Sendable {
    public let request_id: Int64
    public let delta: String
    public let is_reasoning: Bool
    public init(request_id: Int64, delta: String, is_reasoning: Bool) {
        self.request_id = request_id
        self.delta = delta
        self.is_reasoning = is_reasoning
    }
}

public struct StreamDone: Sendable {
    public let request_id: Int64
    public init(request_id: Int64) {
        self.request_id = request_id
    }
}

public struct StreamError: Sendable {
    public let request_id: Int64
    public let message: String
    public init(request_id: Int64, message: String) {
        self.request_id = request_id
        self.message = message
    }
}

public struct StreamStart: Sendable {
    public let request_id: Int64
    public init(request_id: Int64) {
        self.request_id = request_id
    }
}

public struct TestResult: Sendable {
    public let ok: Bool
    public let error: String?
    public let models: [String]?
    public init(ok: Bool, error: String?, models: [String]?) {
        self.ok = ok
        self.error = error
        self.models = models
    }
}

private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode__List_String_(_ v: [String]) -> RivetValue { .list(v.map(encode_String)) }
private func encode__List_List_String_(_ v: [[String]]) -> RivetValue { .list(v.map(encode__List_String_)) }
private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode_StreamStart(_ v: StreamStart) -> RivetValue { .list([encode_Int64(v.request_id)]) }
private func encode_Bytes(_ v: Data) -> RivetValue { .bytes(v) }
private func encode_EditTextBox(_ v: EditTextBox) -> RivetValue { .list([encode_Int64(v.page), encode_Int64(v.x_ratio_milli), encode_Int64(v.y_ratio_milli), encode_String(v.text), encode_Int64(v.size)]) }
private func encode__List_EditTextBox_(_ v: [EditTextBox]) -> RivetValue { .list(v.map(encode_EditTextBox)) }
private func encode__List_Int64_(_ v: [Int64]) -> RivetValue { .list(v.map(encode_Int64)) }
private func encode_EpubTocItem(_ v: EpubTocItem) -> RivetValue { .list([encode_String(v.title), encode_Int64(v.chapter), encode_Int64(v.level)]) }
private func encode__List_EpubTocItem_(_ v: [EpubTocItem]) -> RivetValue { .list(v.map(encode_EpubTocItem)) }
private func encode_EpubView(_ v: EpubView) -> RivetValue { .list([encode_String(v.title), encode_Int64(v.chapters), encode__List_EpubTocItem_(v.toc)]) }
private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode_RecentEntry(_ v: RecentEntry) -> RivetValue { .list([encode_String(v.path), encode_Int64(v.page), encode_Int64(v.scroll_ratio_scaled), encode_Int64(v.last_read_ms)]) }
private func encode__List_RecentEntry_(_ v: [RecentEntry]) -> RivetValue { .list(v.map(encode_RecentEntry)) }
private func encode_TargetLanguage(_ v: TargetLanguage) -> RivetValue { .string(v.rawValue) }
private func encode_SettingsView(_ v: SettingsView) -> RivetValue { .list([encode_String(v.provider), encode_String(v.base_url), encode_String(v.model), encode_TargetLanguage(v.target_language), encode_String(v.view_mode), encode_Bool(v.annotation_sidecar), encode_Bool(v.has_api_key), encode__List_RecentEntry_(v.recent)]) }
private func encode_Void(_ v: Void) -> RivetValue { .null }
private func encode_ProviderPreset(_ v: ProviderPreset) -> RivetValue { .list([encode_String(v.id), encode_String(v.label), encode_String(v.base_url), encode_String(v.default_model), encode_Bool(v.needs_key)]) }
private func encode__List_ProviderPreset_(_ v: [ProviderPreset]) -> RivetValue { .list(v.map(encode_ProviderPreset)) }
private func encode_SettingsUpdate(_ v: SettingsUpdate) -> RivetValue { .list([encode_String(v.provider), encode_String(v.base_url), encode_String(v.model), encode_TargetLanguage(v.target_language), encode_String(v.view_mode), encode_Bool(v.annotation_sidecar)]) }
private func encode_SummarizeMode(_ v: SummarizeMode) -> RivetValue { .string(v.rawValue) }
private func encode__Optional_String_(_ v: String?) -> RivetValue { v.map(encode_String) ?? .null }
private func encode__Optional_List_String_(_ v: [String]?) -> RivetValue { v.map(encode__List_String_) ?? .null }
private func encode_TestResult(_ v: TestResult) -> RivetValue { .list([encode_Bool(v.ok), encode__Optional_String_(v.error), encode__Optional_List_String_(v.models)]) }
private func encode_StreamChunk(_ v: StreamChunk) -> RivetValue { .list([encode_Int64(v.request_id), encode_String(v.delta), encode_Bool(v.is_reasoning)]) }
private func encode_StreamDone(_ v: StreamDone) -> RivetValue { .list([encode_Int64(v.request_id)]) }
private func encode_StreamError(_ v: StreamError) -> RivetValue { .list([encode_Int64(v.request_id), encode_String(v.message)]) }

private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode__List_String_(_ v: RivetValue) throws -> [String] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List String)") }; return try xs.map(decode_String) }
private func decode__List_List_String_(_ v: RivetValue) throws -> [[String]] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List (List String))") }; return try xs.map(decode__List_String_) }
private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode_StreamStart(_ v: RivetValue) throws -> StreamStart { guard case .list(let xs) = v, xs.count == 1 else { throw RivetGeneratedError.typeMismatch("StreamStart") }; return StreamStart(request_id: try decode_Int64(xs[0])) }
private func decode_Bytes(_ v: RivetValue) throws -> Data { guard case .bytes(let x) = v else { throw RivetGeneratedError.typeMismatch("Bytes") }; return x }
private func decode_EditTextBox(_ v: RivetValue) throws -> EditTextBox { guard case .list(let xs) = v, xs.count == 5 else { throw RivetGeneratedError.typeMismatch("EditTextBox") }; return EditTextBox(page: try decode_Int64(xs[0]), x_ratio_milli: try decode_Int64(xs[1]), y_ratio_milli: try decode_Int64(xs[2]), text: try decode_String(xs[3]), size: try decode_Int64(xs[4])) }
private func decode__List_EditTextBox_(_ v: RivetValue) throws -> [EditTextBox] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List EditTextBox)") }; return try xs.map(decode_EditTextBox) }
private func decode__List_Int64_(_ v: RivetValue) throws -> [Int64] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List Int64)") }; return try xs.map(decode_Int64) }
private func decode_EpubTocItem(_ v: RivetValue) throws -> EpubTocItem { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("EpubTocItem") }; return EpubTocItem(title: try decode_String(xs[0]), chapter: try decode_Int64(xs[1]), level: try decode_Int64(xs[2])) }
private func decode__List_EpubTocItem_(_ v: RivetValue) throws -> [EpubTocItem] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List EpubTocItem)") }; return try xs.map(decode_EpubTocItem) }
private func decode_EpubView(_ v: RivetValue) throws -> EpubView { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("EpubView") }; return EpubView(title: try decode_String(xs[0]), chapters: try decode_Int64(xs[1]), toc: try decode__List_EpubTocItem_(xs[2])) }
private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode_RecentEntry(_ v: RivetValue) throws -> RecentEntry { guard case .list(let xs) = v, xs.count == 4 else { throw RivetGeneratedError.typeMismatch("RecentEntry") }; return RecentEntry(path: try decode_String(xs[0]), page: try decode_Int64(xs[1]), scroll_ratio_scaled: try decode_Int64(xs[2]), last_read_ms: try decode_Int64(xs[3])) }
private func decode__List_RecentEntry_(_ v: RivetValue) throws -> [RecentEntry] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List RecentEntry)") }; return try xs.map(decode_RecentEntry) }
private func decode_TargetLanguage(_ v: RivetValue) throws -> TargetLanguage { guard case .string(let x) = v, let result = TargetLanguage(rawValue: x) else { throw RivetGeneratedError.typeMismatch("TargetLanguage") }; return result }
private func decode_SettingsView(_ v: RivetValue) throws -> SettingsView { guard case .list(let xs) = v, xs.count == 8 else { throw RivetGeneratedError.typeMismatch("SettingsView") }; return SettingsView(provider: try decode_String(xs[0]), base_url: try decode_String(xs[1]), model: try decode_String(xs[2]), target_language: try decode_TargetLanguage(xs[3]), view_mode: try decode_String(xs[4]), annotation_sidecar: try decode_Bool(xs[5]), has_api_key: try decode_Bool(xs[6]), recent: try decode__List_RecentEntry_(xs[7])) }
private func decode_Void(_ v: RivetValue) throws -> Void { guard case .null = v else { throw RivetGeneratedError.typeMismatch("Void") } }
private func decode_ProviderPreset(_ v: RivetValue) throws -> ProviderPreset { guard case .list(let xs) = v, xs.count == 5 else { throw RivetGeneratedError.typeMismatch("ProviderPreset") }; return ProviderPreset(id: try decode_String(xs[0]), label: try decode_String(xs[1]), base_url: try decode_String(xs[2]), default_model: try decode_String(xs[3]), needs_key: try decode_Bool(xs[4])) }
private func decode__List_ProviderPreset_(_ v: RivetValue) throws -> [ProviderPreset] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List ProviderPreset)") }; return try xs.map(decode_ProviderPreset) }
private func decode_SettingsUpdate(_ v: RivetValue) throws -> SettingsUpdate { guard case .list(let xs) = v, xs.count == 6 else { throw RivetGeneratedError.typeMismatch("SettingsUpdate") }; return SettingsUpdate(provider: try decode_String(xs[0]), base_url: try decode_String(xs[1]), model: try decode_String(xs[2]), target_language: try decode_TargetLanguage(xs[3]), view_mode: try decode_String(xs[4]), annotation_sidecar: try decode_Bool(xs[5])) }
private func decode_SummarizeMode(_ v: RivetValue) throws -> SummarizeMode { guard case .string(let x) = v, let result = SummarizeMode(rawValue: x) else { throw RivetGeneratedError.typeMismatch("SummarizeMode") }; return result }
private func decode__Optional_String_(_ v: RivetValue) throws -> String? { if case .null = v { return nil }; return try decode_String(v) }
private func decode__Optional_List_String_(_ v: RivetValue) throws -> [String]? { if case .null = v { return nil }; return try decode__List_String_(v) }
private func decode_TestResult(_ v: RivetValue) throws -> TestResult { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("TestResult") }; return TestResult(ok: try decode_Bool(xs[0]), error: try decode__Optional_String_(xs[1]), models: try decode__Optional_List_String_(xs[2])) }
private func decode_StreamChunk(_ v: RivetValue) throws -> StreamChunk { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("StreamChunk") }; return StreamChunk(request_id: try decode_Int64(xs[0]), delta: try decode_String(xs[1]), is_reasoning: try decode_Bool(xs[2])) }
private func decode_StreamDone(_ v: RivetValue) throws -> StreamDone { guard case .list(let xs) = v, xs.count == 1 else { throw RivetGeneratedError.typeMismatch("StreamDone") }; return StreamDone(request_id: try decode_Int64(xs[0])) }
private func decode_StreamError(_ v: RivetValue) throws -> StreamError { guard case .list(let xs) = v, xs.count == 2 else { throw RivetGeneratedError.typeMismatch("StreamError") }; return StreamError(request_id: try decode_Int64(xs[0]), message: try decode_String(xs[1])) }

public enum RivetEvent: Sendable {
    case stream_chunk(StreamChunk)
    case stream_done(StreamDone)
    case stream_error(StreamError)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "stream-chunk": return .stream_chunk(try decode_StreamChunk(value))
        case "stream-done": return .stream_done(try decode_StreamDone(value))
        case "stream-error": return .stream_error(try decode_StreamError(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func chat(context_text: String, context_label: String, history: [[String]], user_message: String) async throws -> StreamStart {
        let result = try await client.call("chat", arguments: [encode_String(context_text), encode_String(context_label), encode__List_List_String_(history), encode_String(user_message)])
        return try decode_StreamStart(result)
    }
    public func edit_append_doc(path: String, other_path: String) async throws -> Data {
        let result = try await client.call("edit-append-doc", arguments: [encode_String(path), encode_String(other_path)])
        return try decode_Bytes(result)
    }
    public func edit_bake_text(path: String, watermark_text: String, watermark_size: Int64, watermark_opacity_milli: Int64, boxes: [EditTextBox]) async throws -> Data {
        let result = try await client.call("edit-bake-text", arguments: [encode_String(path), encode_String(watermark_text), encode_Int64(watermark_size), encode_Int64(watermark_opacity_milli), encode__List_EditTextBox_(boxes)])
        return try decode_Bytes(result)
    }
    public func edit_delete_pages(path: String, pages: [Int64]) async throws -> Data {
        let result = try await client.call("edit-delete-pages", arguments: [encode_String(path), encode__List_Int64_(pages)])
        return try decode_Bytes(result)
    }
    public func edit_extract_pages(path: String, pages: [Int64]) async throws -> Data {
        let result = try await client.call("edit-extract-pages", arguments: [encode_String(path), encode__List_Int64_(pages)])
        return try decode_Bytes(result)
    }
    public func edit_insert_blank_after(path: String, page: Int64) async throws -> Data {
        let result = try await client.call("edit-insert-blank-after", arguments: [encode_String(path), encode_Int64(page)])
        return try decode_Bytes(result)
    }
    public func edit_rotate_pages(path: String, pages: [Int64], delta: Int64) async throws -> Data {
        let result = try await client.call("edit-rotate-pages", arguments: [encode_String(path), encode__List_Int64_(pages), encode_Int64(delta)])
        return try decode_Bytes(result)
    }
    public func epub_chapter_html(path: String, index: Int64) async throws -> Data {
        let result = try await client.call("epub-chapter-html", arguments: [encode_String(path), encode_Int64(index)])
        return try decode_Bytes(result)
    }
    public func epub_chapter_text(path: String, index: Int64) async throws -> String {
        let result = try await client.call("epub-chapter-text", arguments: [encode_String(path), encode_Int64(index)])
        return try decode_String(result)
    }
    public func epub_doc_text(path: String, max_chapters: Int64, cap_chars: Int64) async throws -> String {
        let result = try await client.call("epub-doc-text", arguments: [encode_String(path), encode_Int64(max_chapters), encode_Int64(cap_chars)])
        return try decode_String(result)
    }
    public func epub_open(path: String) async throws -> EpubView {
        let result = try await client.call("epub-open", arguments: [encode_String(path)])
        return try decode_EpubView(result)
    }
    public func get_annotations(pdf_path: String, sidecar: Bool) async throws -> Data {
        let result = try await client.call("get-annotations", arguments: [encode_String(pdf_path), encode_Bool(sidecar)])
        return try decode_Bytes(result)
    }
    public func get_recents() async throws -> [RecentEntry] {
        let result = try await client.call("get-recents", arguments: [])
        return try decode__List_RecentEntry_(result)
    }
    public func get_settings() async throws -> SettingsView {
        let result = try await client.call("get-settings", arguments: [])
        return try decode_SettingsView(result)
    }
    public func initialize() async throws -> Void {
        let result = try await client.call("initialize", arguments: [])
        return try decode_Void(result)
    }
    public func list_presets() async throws -> [ProviderPreset] {
        let result = try await client.call("list-presets", arguments: [])
        return try decode__List_ProviderPreset_(result)
    }
    public func save_api_key(key: String) async throws -> Void {
        let result = try await client.call("save-api-key", arguments: [encode_String(key)])
        return try decode_Void(result)
    }
    public func save_settings(update: SettingsUpdate) async throws -> SettingsView {
        let result = try await client.call("save-settings", arguments: [encode_SettingsUpdate(update)])
        return try decode_SettingsView(result)
    }
    public func set_annotations(pdf_path: String, sidecar: Bool, data: Data) async throws -> Void {
        let result = try await client.call("set-annotations", arguments: [encode_String(pdf_path), encode_Bool(sidecar), encode_Bytes(data)])
        return try decode_Void(result)
    }
    public func set_locale(code: String) async throws -> Void {
        let result = try await client.call("set-locale", arguments: [encode_String(code)])
        return try decode_Void(result)
    }
    public func split_paragraphs(text: String) async throws -> [String] {
        let result = try await client.call("split-paragraphs", arguments: [encode_String(text)])
        return try decode__List_String_(result)
    }
    public func stop_stream(request_id: Int64) async throws -> Void {
        let result = try await client.call("stop-stream", arguments: [encode_Int64(request_id)])
        return try decode_Void(result)
    }
    public func summarize_text(text: String, mode: SummarizeMode) async throws -> StreamStart {
        let result = try await client.call("summarize-text", arguments: [encode_String(text), encode_SummarizeMode(mode)])
        return try decode_StreamStart(result)
    }
    public func test_connection(base_url: String, api_key: String, model: String) async throws -> TestResult {
        let result = try await client.call("test-connection", arguments: [encode_String(base_url), encode_String(api_key), encode_String(model)])
        return try decode_TestResult(result)
    }
    public func translate_text(text: String, target: TargetLanguage) async throws -> StreamStart {
        let result = try await client.call("translate-text", arguments: [encode_String(text), encode_TargetLanguage(target)])
        return try decode_StreamStart(result)
    }
    public func update_recents(path: String, page: Int64, scroll_ratio_scaled: Int64) async throws -> Void {
        let result = try await client.call("update-recents", arguments: [encode_String(path), encode_Int64(page), encode_Int64(scroll_ratio_scaled)])
        return try decode_Void(result)
    }

    // Shared state
    public func getBackend_locale() async throws -> String {
        let result = try await client.getState("backend-locale")
        return try decode_String(result)
    }
    @discardableResult
    public func setBackend_locale(_ value: String) async throws -> String {
        let result = try await client.setState("backend-locale", value: encode_String(value))
        return try decode_String(result)
    }
}
